# Generated by Django 3.2.8 on 2021-12-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, verbose_name='لینک مطلب'),
        ),
    ]
